### ISSUE TITLE
[hybrid-only|accessibility] dotbracket string wrong

### ISSUE THREAD

**Issue by martin-mann** [BackofenLab/RNA-Playground#2]
The returned hybrid structures show an additional leading `.` for the second sequence's dotplot-structure.

eg. input
```
S1 = S2 = CCCCGGG
```
results e.g. in
```
(.(((((X..))))))
```
where the dot after the `X` is to be removed. 

this problem is present for both hybrid-only as well as accessibility-based prediction

**Comment by mostafa-mahmoud** [comment]
I think we can close this issue, @martin-mann You can reopen if it wasn't solved.
