### ISSUE TITLE
hybrid : structure incorrect

### ISSUE THREAD

**Issue by martin-raden** [BackofenLab/RNA-Playground#21]
The example
```
GGUCCAC
GCC
```
should yield 3 base pairs (see cofold), but only 2 reported

**Comment by mostafa-mahmoud** [comment]
Isn't the 2nd sequence reversed? because if the second sequence is CCG it puts 3 base pairs.

**Comment by martin-raden** [comment]
nope, dont expect the reversed sequence in input.

reversing is only done internally to keep indexing easier. But the user provides both sequences in 5' to 3' direction, such that within interaction visualization the first runs from left to right and the second from right to left (which is "corrected" via the reversing)

so please adapt accordingly (actually I think only the input/output handling has to be touched. the computation should be fine)
