### ISSUE TITLE
hybrid : all optimal traceback?

### ISSUE THREAD

**Issue by martin-raden** [BackofenLab/RNA-Playground#22]
would be cool, if the list of structures would contain all possible optimal tracebacks/structures..

if you have the time. think the code should be similar to what we discussed for the other stuff..

**Comment by mostafa-mahmoud** [comment]
Do you have an example that it's not doing that?
Because the current state should be printing all optimal tracebacks upto 14.

**Comment by martin-raden** [comment]
mhh... now that you say so.. maybe I used a "unique solution" example while testing.. sorry! ;)
