### ISSUE TITLE
[accesibility-based] Pu2 values wrong

### ISSUE THREAD

**Issue by martin-mann** [BackofenLab/RNA-Playground#3]
Hi guys,

I am quite sure that the RNAup implementation (DPAlgorithm_rnaup) has a bug and does not do the following:

- the computation of Pu2 (Tables[2]) has to be based on the *reverse* sequence!

As far as I get it, you are using just input sequence2.

Thus the following example : `S1=GGUCCAC, S2=AAAAAAGGGACC`
shows the problem: the accessible region (1-6) of S2 is wrongly applied to its second half (7-12) causing a wrong prediction!

The clean (and preferrred) way to fix this would be to rename "sequence2" to "sequence2reversed" in nussinovmatrix4d.js and to adapt the two algorithms accordingly. Note this covers:

- [x] renaming of the variable (check dependencies in other script files)
- [x] reversing S2 input in init() function
- [ ] adaption of S2 element access (currently via "length-j" etc)
- [ ] adaption of 4dMatrix/trace access (currently also using some "length-..")
- [x] adaption of visualization (might need another reverse? depending on what data is accessed)
- [x] test if outcome is still working/correct 

Thanks,
Martin

**Comment by mostafa-mahmoud** [comment]
@martin-mann Should the 2nd sequence be also reversed for Hybrid and Cofold?

**Comment by martin-mann** [comment]
the 2nd sequence has to be reversed for hybrid as well, but seems to be in place already..

for cofold no reversal is needed, since both sequences are concatenated
