### ISSUE TITLE
[accessibility] result list incomplete ?!

### ISSUE THREAD

**Issue by martin-mann** [BackofenLab/RNA-Playground#6]
The result list for accessibilitity-based interaction prediction seems to be incomplete. 

the following input
```
S1 = S2 = CCCCGGG
```
should produce the symmetric results
```
....(..X...)...
...(...X....)..
```
but produces only the first one.

Please check, might already be resolved with issue #3 but not sure, since the Pus for this example are symmetric and thus no indexing problem present.

**Comment by mostafa-mahmoud** [comment]
@martin-mann We tried debugging this, and we think it's not a bug, and that the first output is given higher score than the second output. Do you have an example with values to confirm?

**Comment by martin-mann** [comment]
I come to the same conclusion.

when extending the sequences with another `G` (making the ED values symmetric), one gets the expected behaviour..

thanks for testing
